ca/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .views import PostCreateView,POCCreateView

urlpatterns = [
    path('home/', views.home, name='home'),
    path('ideas/', views.ideas, name='ideas'),
    path('poc/', views.poc,name="poc"),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('poc/new/', POCCreateView.as_view(), name='poc-create'),
    path('poc/new_csv/',views.poccsv, name='poc-csv-create'),
]

ca_portal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
# making admin non accessible my non staff users
from .admin import admin_view
admin.site.admin_view = admin_view
#login, go to left navbar to access admin
urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('dashboard.urls')),
    path('submissions/', include('submissions.urls')),
    

   
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

handler404 = 'ca_portal.views.error_404'
handler500 = 'ca_portal.views.error_500'

users/urls.py
from django.urls import path
from users import views as user_views
from django.contrib.auth import views as auth_views
from .views import VerificationView

urlpatterns = [
    path('register-single/', user_views.register_single_user, name='register_single'),
    path('register-group/', user_views.register_group_user, name='register_group'),
    path('login/', user_views.loginPage, name='login'),
    path('profile/', user_views.profile, name='profile'),
    path('activate/<uidb64>/<token>', VerificationView.as_view(), name="activate"),
    path('logout/', auth_views.LogoutView.as_view(template_name='dashboard/landing_page.html'), name='logout'),
    # Password reset urls
    path("password_reset", user_views.password_reset_request, name="password_reset"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="users/password/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password/password_reset_complete.html'), name='password_reset_complete'),
]

users/models.py
import uuid
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager
from phonenumber_field.modelfields import PhoneNumberField
from .utils import create_new_ref_number
from PIL import Image


class CustomAccountManager(BaseUserManager):
    def create_superuser(self, email, firstname, password, **other_fields):
        other_fields.setdefault('is_staff', True)
        other_fields.setdefault('is_superuser', True)
        other_fields.setdefault('is_active', True)
        other_fields.setdefault('username', 'superuser')
        if other_fields.get('is_staff') is not True:
            raise ValueError(
                'Superuser must be assigned to is_staff=True.')
        if other_fields.get('is_superuser') is not True:
            raise ValueError(
                'Superuser must be assigned to is_superuser=True.')
        return self.create_user(email,  firstname, password, "email", **other_fields)

    def create_user(self, email, firstname, password, provider, **other_fields):
        if not email:
            raise ValueError(_('You must provide an email address'))
        email = self.normalize_email(email)
        user = self.model(email=email,
                          firstname=firstname, provider=provider, ** other_fields)
        user.set_password(password)
        user.save()
        return user


# Username for admin is admin, superuser is superuser
# firstname field stores the user full name of the User


class NewUser(AbstractBaseUser, PermissionsMixin):
    id = models.SlugField(primary_key=True, default=uuid.uuid4)
    alcherid = models.CharField(
        max_length=9, blank=True, unique=True, default=create_new_ref_number)

    img = models.ImageField(
        upload_to="image-uploads/", default='image-uploads/user.png')
    email = models.EmailField(_('email address'), unique=True)
    username = models.CharField(max_length=150, unique=False, default="user")
    firstname = models.CharField(max_length=150, blank=True)
    phone = PhoneNumberField(unique=False, blank=True)
    graduation_year = models.CharField(max_length=200, unique=False)
    college_state = models.CharField(max_length=200, unique=False)
    college_city = models.CharField(max_length=200, unique=False)
    college_name = models.CharField(max_length=200, unique=False)
    position_of_responsibility = models.CharField(
        max_length=200, unique=False, blank=True)
    interested_modules = models.CharField(
        max_length=200, unique=False, blank=True)
    # Referral fields
    referred_by = models.CharField(
        max_length=9, blank=True)
    # referred_by_user = models.ForeignKey(
    #     'NewUser', blank=True, on_delete=models.CASCADE)
    referrals = models.IntegerField(default=0)
    # other fields

    date_joined = models.DateTimeField(default=timezone.now)
    provider = models.CharField(max_length=200, unique=False, default="email")
    about = models.TextField(_('about'), max_length=500, blank=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    objects = CustomAccountManager()
    points = models.IntegerField(default=50)
    tasks = models.IntegerField(default=0)
    instahandle = models.CharField(max_length=200, unique=False, default="")

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['firstname']

    def __str__(self):
        return str(self.id)

    def save(self, *args, **kwargs):
        super().save()
        img = Image.open(self.img.path)
        width, height = img.size  # Get dimensions

        if width > 300 and height > 300:
            # keep ratio but shrink down
            img.thumbnail((width, height))

        # check which one is smaller
        if height < width:
            # make square by cutting off equal amounts left and right
            left = (width - height) / 2
            right = (width + height) / 2
            top = 0
            bottom = height
            img = img.crop((left, top, right, bottom))

        elif width < height:
            # make square by cutting off bottom
            left = 0
            right = width
            top = 0
            bottom = width
            img = img.crop((left, top, right, bottom))

        if width > 300 and height > 300:
            img.thumbnail((300, 300))

        img.save(self.img.path)
        


class UserSingle(models.Model):
    user = models.ForeignKey('NewUser', on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user.id} Profile'


class UserGroup(models.Model):
    id = models.SlugField(primary_key=True, default=uuid.uuid4)
    leader = models.ForeignKey(
        'NewUser', related_name='leader', on_delete=models.CASCADE)
    executive = models.ForeignKey(
        'NewUser', related_name='executive', on_delete=models.CASCADE)
    college_state = models.CharField(max_length=200, unique=False)
    college_city = models.CharField(max_length=200, unique=False)
    college_name = models.CharField(max_length=200, unique=False)
    

    referred_by = models.CharField(
        max_length=9, blank=True)
    # referred_by_user = models.ForeignKey(
    #     'NewUser', blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.id)

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages

from dashboard.models import Notifications
from .forms import SingleUserRegisterForm, GroupUserRegisterForm, GroupUserRegisterFormForSingle, UserUpdateForm
from django.contrib.auth import authenticate, login
from django.urls import reverse
from .models import NewUser
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.contrib.sites.shortcuts import get_current_site
from .utils import token_generator
from django.views import View
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.core.mail import send_mail, BadHeaderError
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth import get_user_model
from django.template.loader import render_to_string
from django.contrib.auth.tokens import default_token_generator
from django.db.models.query_utils import Q
from .models import UserSingle
from django.core.mail import EmailMultiAlternatives
from django.utils.html import strip_tags
User = get_user_model()

def register_single_user(request):
    if request.user.is_authenticated:
        return redirect('dashboard_page')
    else:
        single_user_form = SingleUserRegisterForm(request.POST or None)
        if request.method == 'POST':
            if single_user_form.is_valid():
                result = single_user_form.save(commit=False)

                if(request.POST.get('referred_by')):
                    user = NewUser.objects.get(
                        alcherid=request.POST.get('referred_by'))
                    # result.referred_by_user=user
                    result.points = 25
                    result.save()
                    user.referrals += 1
                    user.points += 25
                    user.save()
                else:
                    result.save()

                user = NewUser.objects.get(email=request.POST.get('email'))
                userSingle = UserSingle()
                userSingle.user = user
                userSingle.save()
                uidb64 = urlsafe_base64_encode(force_bytes(user.pk))
                domain = get_current_site(request).domain
                link = reverse('activate', kwargs={
                               'uidb64': uidb64, 'token': token_generator.make_token(user)})
                subject = "Activate your account"
                email_template_name = "users/email_verify_mail.html"
                firstname = request.POST.get('firstname')
                c = {
                    "firstname": firstname,
                    "link": 'https://'+domain+link,
                }
                email = render_to_string(email_template_name, c)
                try:
                    message = EmailMultiAlternatives(
                        subject=subject,
                        body="mail testing",
                        from_email='Alcheringa Campus Ambassador <schedulerevent9@gmail.com>',
                        to=[user.email]
                    )
                    message.attach_alternative(email, "text/html")
                    message.send(fail_silently=False)

                    # send_mail(subject, email, 'Alcheringa Campus Ambassador <schedulerevent9@gmail.com>', [
                    #           user.email], fail_silently=False)
                except BadHeaderError:
                    return HttpResponse('Invalid header found.')
                messages.success(
                    request, ('Registration successful. Check your mail for the link to activate your account.'))
                return redirect('register_single')
        else:
            single_user_form = SingleUserRegisterForm()
        return render(request, 'users/register_single.html', {'single_user_register_form': single_user_form, })


def register_group_user(request):
    if request.user.is_authenticated:
        return redirect('dashboard_page')
    else:
        group_user_form = GroupUserRegisterForm(request.POST or None)
        single_user_form_1 = GroupUserRegisterFormForSingle(
            request.POST or None, prefix='form_1')
        single_user_form_2 = GroupUserRegisterFormForSingle(
            request.POST or None, prefix='form_2')
        if request.method == 'POST':
            if single_user_form_1.is_valid() and single_user_form_2.is_valid() and group_user_form.is_valid():
                single_form_1_result = single_user_form_1.save(commit=False)
                single_form_1_result.college_state = request.POST.get(
                    'college_state')
                single_form_1_result.college_city = request.POST.get(
                    'college_city')
                single_form_1_result.college_name = request.POST.get(
                    'college_name')
                single_form_1_result.referred_by = request.POST.get(
                    'referred_by')
                single_form_1_result.set_password(
                    request.POST.get('password1'))
                single_form_1_result.username = "Groupuser"
                single_form_1_result.save()
                # 2nd form
                single_form_2_result = single_user_form_2.save(commit=False)
                single_form_2_result.college_state = request.POST.get(
                    'college_state')
                single_form_2_result.college_city = request.POST.get(
                    'college_city')
                single_form_2_result.college_name = request.POST.get(
                    'college_name')
                single_form_2_result.referred_by = request.POST.get(
                    'referred_by')
                single_form_2_result.set_password(
                    request.POST.get('password1'))
                single_form_2_result.username = "Groupuser"
                single_form_2_result.save()

                user_1 = NewUser.objects.get(
                    email=request.POST.get('form_1-email'))
                user_2 = NewUser.objects.get(
                    email=request.POST.get('form_2-email'))

                group_form_result = group_user_form.save(commit=False)
                group_form_result.leader = user_1
                group_form_result.executive = user_2

                if(request.POST.get('referred_by')):
                    user = NewUser.objects.get(
                        alcherid=request.POST.get('referred_by'))
                    # result.referred_by_user=user
                    group_form_result.referred_by = request.POST.get(
                        'referred_by')
                    user.referrals += 1
                    user.save()
                    group_form_result.save()
                else:
                    group_form_result.save()
                # SEnding mail to leader

                uidb64 = urlsafe_base64_encode(force_bytes(user_1.pk))
                domain = get_current_site(request).domain
                link = reverse('activate', kwargs={
                               'uidb64': uidb64, 'token': token_generator.make_token(user_1)})
                subject = "Activate your account"
                email_template_name = "users/email_verify_mail.html"
                firstname = user_1.firstname
                c = {
                    "firstname": firstname,
                    "link": 'https://'+domain+link,
                }
                email1 = render_to_string(email_template_name, c)

                # sending mail to executive

                uidb64 = urlsafe_base64_encode(force_bytes(user_2.pk))
                domain = get_current_site(request).domain
                link = reverse('activate', kwargs={
                               'uidb64': uidb64, 'token': token_generator.make_token(user_2)})
                subject = "Activate your account"
                email_template_name = "users/email_verify_mail.html"
                firstname = user_2.firstname
                c = {
                    "firstname": firstname,
                    "link": 'https://'+domain+link,
                }
                email2 = render_to_string(email_template_name, c)
                try:
                    message = EmailMultiAlternatives(
                        subject=subject,
                        body="mail testing",
                        from_email='Alcheringa Campus Ambassador <schedulerevent9@gmail.com>',
                        to=[user_1.email]
                    )
                    message2 = EmailMultiAlternatives(
                        subject=subject,
                        body="mail testing",
                        from_email='Alcheringa Campus Ambassador <schedulerevent9@gmail.com>',
                        to=[user_2.email]
                    )
                    message.attach_alternative(email1, "text/html")
                    message.send(fail_silently=False)
                    message2.attach_alternative(email2, "text/html")
                    message2.send(fail_silently=False)
                    # send_mail(subject, email1, 'Alcheringa Campus Ambassador <schedulerevent9@gmail.com>', [
                    #           user_1.email], fail_silently=False)
                    # send_mail(subject, email2, 'Alcheringa Campus Ambassador <schedulerevent9@gmail.com>', [
                    #           user_2.email], fail_silently=False)
                except BadHeaderError:
                    return HttpResponse('Invalid header found.')
                messages.success(
                    request, ('Registration successful. Check your mail for the link to activate your account.'))
                return redirect('register_group')
        # else:
        #     group_user_form = GroupUserRegisterForm()
        #     single_user_form_1 = GroupUserRegisterFormForSingle()
        #     single_user_form_2 = GroupUserRegisterFormForSingle()

templates/users/email_verify_mail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    
   
  </head>
  <body style="background: #e5e5e5">
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet" />
    <div
      style="background-color: #ffffff; width: 1000px; height: 1150px"
      class="my-40 mx-20 p-4"
    >
      <div
        style="
          background-color: #109cf1;
          height: 167.000000301315px;
          width: 966.0000017429359px;
          left: 29.263671875px;
          top: 40.97486114501953px;
          border-radius: 16px;
        "
        class="flex"
      >
        <div
          style="
            background-color: #109cf1;
            margin-top: 50px;
            margin-left: 300px;
          "
          class=""
        >
          <img src="{% static 'images/ca-mail.svg' %}" alt="" />
        </div>
        <div>
          <div
            style="
              color: #ffffff;
              text-align: center;
              margin-top: 40px;
              font-size: 30px;
            "
            class="text-7x1 font-bold"
          >
            ALCHERINGA
          </div>
          <div style="color: #ffffff; text-align: center; font-size: 18px">
            CAMPUS AMBASSADOR
          </div>
        </div>
      </div>

      <div
        style="
          background-color: #b4e3ff;
          height: 924.000001667156px;
          width: 966.0000017429359px;
          left: 30.802734375px;
          top: 232.96869659423828px;
          border-radius: 16px;
          padding-top: 0.5px;
        "
        class="mt-4"
      >
        <div
          style="
            background-color: #ffffff;
            height: 765.0000013802753px;
            width: 943.0000017014373px;
            left: 42.890380859375px;
            top: 243.87215423583984px;
            border-radius: 16px;
          "
          class="ml-2 mt-8"
        >
          <div>
            <h1 class="text-4xl pt-8 pl-8 font-semibold">Hello {{firstname}},</h1>
            <p class="text-2xl mt-10 ml-8">
              Welcome to Alcheringa Campus Ambassador Portal. <br />
              Please click below to verify your account
            </p>
          </div>
          <a href="{{link}}"
            style="
              background-color: #109cf1;
              display: flex;
              flex-direction: row;
              width: 177px;
              margin-left: 30px;
              margin-top: 40px;
              justify-content: center;
              align-items: center;
              padding: 8px 16px;
              box-shadow: 0px 4px 10px rgba(16, 156, 241, 0.24);
              border-radius: 4px;
              transform: rotate(-0.46deg);
            "
          >
            <h1 style="color: #ffffff" class="font-semibold">Verify</h1>
        </a>

          <div>
            <p class="text-2xl mt-10 ml-8">
              If that doesn’t work, please copy and <br />
              paste the below link in your browser.
            </p>
            <a style="color: #109cf1" class="text-2xl mt-4 ml-8" href="{{link}}"
              >{{link}}</a
            >
            <img
              style="
                position: absolute;
                width: 450px;
                height: 450px;
                left: 550.51px;
                top: 560.48px;
              "
              src="{% static 'images/ca-man.svg' %}"
              alt=""
            />
          </div>
          <div>
            <p class="text-2xl mt-20 ml-8">
              Sincerely, <br />
              Alcheringa Web Operations
            </p>
          </div>
          <div>
            <p style="color: #838383" class="text-2xl mt-40 ml-8">
              This is an automated message, please dont reply.
            </p>
          </div>
        </div>
        <div>
          <p
            style="
              font-family: Poppins;
              font-size: 24px;
              font-style: normal;
              font-weight: 400;
              line-height: 36px;
              letter-spacing: 0.01em;
              text-align: center;
            "
            class="mt-10"
          >
            Need more help?
          </p>
          <a
            href="www.alcheringa.in"
            style="
              position: absolute;

              font-family: Poppins;
              font-style: normal;
              font-weight: 600;
              font-size: 18px;
              line-height: 27px;
              text-align: center;
              margin-left: 440px;

              letter-spacing: 0.01em;
              text-decoration-line: underline;

              color: #109cf1;

              transform: rotate(-0.46deg);
            "
            class=""
            >Contact us</a
          >
        </div>
      </div>
    </div>
  </body>
</html>

templates/users/logout.html
{% extends '../basic.html'%}
{%block title%}Alcheringa {%endblock%}
{% block body %}
<h1>Logged Out successfully</h1>
<a href="{% url 'login' %}" class="ml-2">Login Again</a>
{%endblock%}

templates/users/profile.html
{% extends '../basic.html'%}
{%block title%}Profile | Alcheringa {%endblock%}
{% block body %}

<body>
	<div class="bg-blue-50 flex">
		{% include "../navbar.html" %}
		<div class="flex">
			<div class="flex-grow">
				{% include "users/profile_update.html" %}
			</div>
		</div>
	</div>
	</div>

</body>
{%endblock%}
{% block script %}

{% endblock %}

templates/users/profile_update.html
<div class="bg-white flex bg-gray-50 flex-grow">
    <div class="mx-4 flex-grow">
        
        <br>
        <div class="flex m-1">
            <div class=" bg-white max-w-4xl rounded-lg w-screen shadow-md">
                <div class="flex-grow">
                    <div class="py-3 pl-6  text-xl border-b-2 font-normal">Edit profile</div>

                    <br>
                    <div class="mx-10">
                        <div class="container">
                            <img src="{{request.user.img.url}}" width="80px" id="dp-set"class="justify-self-start"
                                alt="profile pic" border="0" class="mx-auto" style="border-radius:9999px;" />
                            <button class="mx-6 bg-gray-200 rounded-full border-black" onclick="dpupload()" style = "transform:translate(30px,-18px) scale(1.5,1.5)">
                                <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20"
                                    fill="currentColor">
                                    <path
                                        d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z" />
                                </svg>
                            </button>
                        </div>
                        <!-- Hiden dp upload -->
                        <form method="POST" enctype="multipart/form-data" class="grid grid-cols-2 gap-2 place-content-end md:place-content-center">{% csrf_token %}
                        <div style="height:0px;overflow:hidden">
                            {{ u_form.img }}
                            
                        </div>

                        <br>
                       
                            <div>
                                <div class="font-medium text-xs text-gray-500 text-left">Full name</div>
                                {{ u_form.firstname }}
                                <hr style = "width: 180px">
                            </div>



                            <div>
                                <div class="font-medium text-xs text-gray-500 text-left ">College</div>
                                {{ u_form.college_name }}
                                <hr style = "width: 180px">
                            </div>


                            <div>
                                <div class="pt-6 font-medium text-xs text-gray-500 text-left">Contact number</div>
                                {{ u_form.phone }}
                                <hr style = "width: 180px">
                            </div>

                            <div>
                                <div class="pt-6 font-medium text-xs text-gray-500 text-left">Email ID</div>
                                {{ request.user.email }}
                                <hr style = "width: 180px">
                            </div>

                            <div>
                                <div class="pt-6 font-medium text-xs text-gray-500 text-left">Instahandle</div>
                                {{  u_form.instahandle }}
                                <hr style = "width: 180px">
                            </div>

                            <div>
                                <div class="pt-6 font-medium text-xs text-gray-500 text-left">College State</div>
                                {{ u_form.college_state }}
                                <hr style = "width: 180px">
                            </div>
                            <div>
                                <div class="pt-6 font-medium text-xs text-gray-500 text-left">College City</div>
                                {{ u_form.college_city }}
                                <hr style = "width: 180px">
                            </div>

                            <div>
                                <div class="pt-6 font-medium text-xs text-gray-500 text-left">Graduation Year
                                </div>
                                {{ u_form.graduation_year }}
                                <hr style = "width: 180px">
                            </div>
                            
                            <div>
                                <div class="pt-6 font-medium text-xs text-gray-500 text-left">Position of Responsibility
                                </div>
                                {{ u_form.position_of_responsibility }}
                                <hr style = "width: 180px">
                            </div>
                            <div>
                                <div class="pt-6 font-medium text-xs text-gray-500 text-left">Interested Modules
                                </div>
                                {{ u_form.interested_modules }}
                                <hr style = "width: 180px">
                            </div>
                            <div>
                                <div class="pt-6 font-medium text-xs text-gray-500 text-left">ALCHERID
                                </div>
                                {{ request.user.alcherid }}
                                <hr style = "width: 180px">
                            </div>
                            <div>
                                <div class="pt-6 font-medium text-xs text-gray-500 text-left">Referrals
                                </div>
                                {{ request.user.referrals }}
                                <hr style = "width: 180px">
                            </div>
                            <br/>
                            <ul class="errorlist" style="color:red">
                                {% if u_form.non_field_errors %}
                                <li>{{ u_form.non_field_errors }}</li>
                                {% endif %}
                                {% for field in u_form %}
                                {% if field.errors %}
                                <ul class="errorlist">
                                    {% for error in field.errors %}
                                    {{ error }}
                                    {% endfor %}
                                </ul>
                                {% endif %}
                                {% endfor %}
                            </ul>
                            <br/>


                            <div class="py-10 submit">
                                <input type="submit"
                                    class="bg-blue-600 hover:bg-blue-700 text-white inline-block py-2 px-4 rounded shadow-sm font-semibold text-base" value="Update details" />
                            </div>

                        </form>

                        <br>
                        






                    </div>
                    <div class="  w-80 border-gray-400 rounded mx-4 m-{5}"></div>
                </div>
            </div>

            {% block script %}
            <script>
                function dpupload() {
                    $("#id_img").click();
                }
                document.getElementById("id_img").addEventListener('change', (event) => {
                    document.getElementById("dp-set").src = URL.createObjectURL(event.target.files[0]);
                });
                
            </script>
            {% endblock %}